PORTNAME=	libpool
PORTVERSION=	1.0
CATEGORIES=	devel

MAINTAINER=	koue@chaosophia.net
COMMENT=	libpool

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	koue
GH_PROJECT=	libpool

CFLAGS+=	-Wall

MAKE_ARGS+=	BINDIR=${PREFIX}/sbin MANDIR=${PREFIX}/man/man

.include <bsd.port.mk>
